### ISSUE TITLE
`Null check operator used on a null value` upon running `flutter build apk --release`

### ISSUE THREAD

**Issue by samikhan69420** [sunarya-thito/shadcn_flutter#146]
I was making an app with this package and it was running fine in debug mode, but when I tried to run my app in release mode or tried to build the release apk, I got this error:

```shell
Null check operator used on a null value
#0      SummaryCollector.visitFunctionExpression (package:vm/transformations/type_flow/summary_collector.dart:1763)
#1      FunctionExpression.accept (package:kernel/ast.dart:8588)
#2      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:975)
#3      SummaryCollector._visitArguments (package:vm/transformations/type_flow/summary_collector.dart:1001)
#4      SummaryCollector.visitConstructorInvocation (package:vm/transformations/type_flow/summary_collector.dart:1756)
#5      ConstructorInvocation.accept (package:kernel/ast.dart:6666)
#6      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:975)
#7      SummaryCollector._visitArguments (package:vm/transformations/type_flow/summary_collector.dart:1001)
#8      SummaryCollector.visitConstructorInvocation (package:vm/transformations/type_flow/summary_collector.dart:1756)
#9      ConstructorInvocation.accept (package:kernel/ast.dart:6666)
#10     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:975)
#11     SummaryCollector.visitReturnStatement (package:vm/transformations/type_flow/summary_collector.dart:2430)
#12     ReturnStatement.accept (package:kernel/ast.dart:10140)
#13     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:978)
#14     List.forEach (dart:core-patch/growable_array.dart:417)
#15     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:2273)
#16     Block.accept (package:kernel/ast.dart:9181)
#17     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:978)
#18     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:838)
#19     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1912)
#20     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:399)
#21     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:288)
#22     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1793)
#23     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1736)
#24     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1941)
#25     transformComponent (package:vm/transformations/type_flow/transformer.dart:123)
#26     runGlobalTransformations (package:vm/kernel_front_end.dart:632)
#27     compileToKernel (package:vm/kernel_front_end.dart:544)
<asynchronous suspension>
#28     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:660)
<asynchronous suspension>
#29     starter (package:frontend_server/starter.dart:109)
<asynchronous suspension>
#30     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/sami/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 23s
Running Gradle task 'assembleRelease'...                           24.2s
Gradle task assembleRelease failed with exit code 1
```

This only gets fixed when I remove the `shadcn_flutter` package from my `pubspec.yaml`.

**Comment by sunarya-thito** [comment]
Try `flutter clean`

**Comment by samikhan69420** [comment]
I did, it didn't fix it.

**Comment by sunarya-thito** [comment]
what version is the shacdn_flutter in your pubspec.yml

**Comment by samikhan69420** [comment]
`shadcn_flutter: ^0.0.22`

**Comment by VenceslavZlatev** [comment]
Can it be related to this issue?

https://github.com/sunarya-thito/shadcn_flutter/issues/143

Its just that i was building on windows and he is building on android

**Comment by sunarya-thito** [comment]
hard to tell, it could be a broken dependency cache?, maybe try `flutter pub cache repair`?
can you maybe try create a new flutter project with shadcn_flutter as dependency and see if the problem still occurs?

**Comment by samikhan69420** [comment]
Ok, so I created a new flutter project and added the dependency and added the `ShadcnApp()` to the root of my project and so far its building the release apk fine without any error. I'm going to try adding additional components to see which one is causing the error.

**Comment by samikhan69420** [comment]
The `TextField()` widget is causing the issue.

**Comment by KRTirtho** [comment]
Originally originated on wasm target, but it's actually a dart `vm` bug. See the issues:
- https://github.com/flutter/flutter/issues/159760
- https://github.com/dart-lang/sdk/issues/57084

It has been fixed in the dart side and Flutter 3.28.0-0.1.pre. This is not caused by `shadcn_flutter` definitely. Btw this is not just limited to android. Same issue occurs in macOS with same error. So it's a dart side issue although not primarily created by the library

I tried to build with 3.28.0-0.1.pre but it fails as `Color`'s new `toARGB32` method isn't implemented for shadcn's `ColorShades` class

<details>
<summary> Logs </summary>

<code>

```shell
../../.pub-cache/hosted/pub.dev/shadcn_flutter-0.0.24/lib/src/theme/color_scheme.dart:49:7: Error: The non-abstract class 'ColorShades' is missing implementations for these members:
 - Color.toARGB32
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ColorShades implements Color, ColorSwatch {
      ^^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/painting.dart:219:7: Context: 'Color.toARGB32' is defined here.
  int toARGB32() {
      ^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevRelease'.
> Process 'command '~/fvm/versions/3.28.0-0.1.pre/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```
</code>
</details>

TBH, it's pretty rare to find vm level (pretty much programming language level) bugs. So some hardcore programming has been done here

**Comment by KRTirtho** [comment]
I tried to find out the issues here. Seems these 2 lines are breaking the dart vm. It's definitely a vm bug as it's perfectly valid dart code:

https://github.com/sunarya-thito/shadcn_flutter/blob/b53520f4e839e824f593c9da44e4b1a8e0a90e47/lib/src/components/form/text_field.dart#L121

https://github.com/sunarya-thito/shadcn_flutter/blob/b53520f4e839e824f593c9da44e4b1a8e0a90e47/lib/src/components/form/text_field.dart#L142

Not sure why it's breaking but commenting out them, fixes the issue. But it'll cause runtime ig

**Comment by KRTirtho** [comment]
This is a far more complex issue probably caused by the `FocusNode` constructor's code.  It's just better to upgrade to Flutter beta channel `>= 3.28.0-0.1.pre` for now until an official patched version of Flutter with patched Dart SDK is released.

I've pushed the change to one of my fork to fix the `ColorShades` not having new `toARGB32` method. This will make it work on both `3.27.x` and `3.28.0-0.1.pre` and will create a PR with it

**Comment by KRTirtho** [comment]
@sunarya-thito please pin this issue. Anyone using 3.27.x will face this problem. Maybe mention it in the README as well

**Comment by Iccr** [comment]
For me I am using Select widget. If I remove select widget from the app, the release builds the apk. but with select widget, itgives me the same error  **Null check operator used on a null value**.  is there any work around? this is blocking the release for my app also.

**Comment by youzhonghui** [comment]
It seems that the issue was resolved by using Flutter 3.27.2 and the master branch shadcn_flutter.
