### ISSUE TITLE
shadcn_app.dart 218:5 [_dispatchAppInitialized]

### ISSUE THREAD

**Issue by cyberpwnn** [sunarya-thito/shadcn_flutter#72]
Makes shadcn_flutter unusable on release mode as the entire app is grey screen error. Doesnt happen on web debug (chrome). Breaks 100% of the time on webkit.

```
TypeError: $this[method] is not a function
dart-sdk/lib/_internal/js_shared/lib/js_interop_unsafe_patch.dart 32:63      JSObjectUnsafeUtilExtension._callMethod
dart-sdk/lib/js_interop_unsafe/js_interop_unsafe.dart 68:7                   JSObjectUnsafeUtilExtension.callMethod
packages/shadcn_flutter/src/platform/platform_implementations_web.dart 9:19  onAppInitialized
packages/shadcn_flutter/src/shadcn_app.dart 218:5                            [_dispatchAppInitialized]
dart-sdk/lib/async/future.dart 431:42                                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:11      internalCallback
```

In chrome on release its obfuscated but 
```
main.dart.js:5992 Uncaught Error: Error: a[b] is not a function
    at Object.blN (main.dart.js:30468:23)
    at Object.Vk (main.dart.js:30471:26)
    at O6.abQ (main.dart.js:97280:9)
    at tear_off.<anonymous> (main.dart.js:3551:79)
    at an1.$0 (main.dart.js:40993:9)
    at aUx.$0 (main.dart.js:40780:8)
```

When adding the preloader bootstrap it still fails (but I dont even want the preloader as i'm using native splashscreen

```
Uncaught (in promise) TypeError: $this[method] is not a function
    at Object.JSObjectUnsafeUtilExtension$124_callMethod [as JSObjectUnsafeUtilExtension|_callMethod] (js_interop_unsafe_patch.dart:32:63)
    at Object.JSObjectUnsafeUtilExtension$124callMethod [as JSObjectUnsafeUtilExtension|callMethod] (js_interop_unsafe.dart:68:7)
    at platform_implementations_web.ShadcnFlutterPlatformImplementations.new.onAppInitialized (platform_implementations_web.dart:9:19)
    at [_dispatchAppInitialized] (shadcn_app.dart:218:5)
    at future.dart:431:42
    at internalCallback (isolate_helper.dart:48:11)
```

For the time being I'm just going to fork & remove all of the js garbage in the package except for the context menu hack.

**Comment by sunarya-thito** [comment]
i pushed 0.0.20 to pub.dev, should be fixed in that version
